name: habitflow
description: "🌱 HabitFlow - Beautiful Habit Tracker. Modern, gamified habit tracking app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  confetti: ^0.7.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Local Storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  
  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.3
  
  # Charts & Analytics
  fl_chart: ^0.68.0
  
  # Date & Time
  intl: ^0.19.0
  timezone: ^0.9.4
  
  # Utilities
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  
  # In-App Purchases
  purchases_flutter: ^6.30.2
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Image & Assets
  cached_network_image: ^3.3.1
  
  # Navigation
  go_router: ^14.2.7
  
  # Animations
  lottie: ^3.1.2
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # Network
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
